services:
  dev:
    image: mcr.microsoft.com/devcontainers/python:3.11
    volumes:
      - ..:/workspaces:cached
    working_dir: /workspaces
    command: sleep infinity
    env_file: .env
    environment:
      PGSSLMODE: "require"
